[package]
name = "bebop-bemu"
version = "0.1.0"
edition = "2021"

[lib]
path = "../../../../../../bebop/src/nodes/bemu/src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "bebop-bemu"
path = "../../../../../../bebop/src/nodes/bemu/src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
snafu = "0.8"
once_cell = "1"
prost = "0.13"
bebop-elf = { path = "../../../../../../bebop/src/nodes/lib/elf" }
bebop-syscall = { path = "../../../../../../bebop/src/nodes/lib/syscall" }
bebop-dtb = { path = "../../../../../../bebop/src/nodes/lib/dtb" }
bebop-uart = { path = "../../../../../../bebop/src/nodes/lib/uart" }
bebop-bank-hash = { path = "../../../../../../bebop/src/nodes/lib/bank-hash" }
bebop-bemu-profile = { path = "../../../../../../bebop/src/nodes/lib/bemu-profile" }
bebop-rushb = { path = "../../../../../../bebop/src/nodes/lib/rushB" }

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
prost-build = "0.13"

[features]
difftest = []
